In [7]:
import pandas as pd

In [8]:
df = pd.read_csv("/workspaces/poetry-demo-test2/toDB/comments_Cleaned.csv")
df_yesterday = pd.read_csv("/workspaces/poetry-demo-test2/toDB/comment_list.csv")

In [9]:
from datetime import date, timedelta
today = date.today()
df['create_date'] = pd.to_datetime(df['create_date']).dt.date
df_yesterday['create_date'] = pd.to_datetime(df_yesterday['create_date']).dt.date
yesterday = date.today() - timedelta(days=1)
df_date = df[df['create_date'] ==  today ]
df_yesterday = df_yesterday[df_yesterday['create_date'] == yesterday]

In [ ]:
df_date = df

In [10]:
df_yesterday

,user_id,nm_id,st_id,rating_star,time_num,time_unit,months_ago,content_clean,create_date,update_date
749118,100726578982543737739,NX,1958,5,12,小時,0.000000,蚵仔煎非常好吃 值得一嚐,2025-05-18,2025-05-18
749119,117399489229503352432,NX,1958,4,15,小時,0.000000,排隊名店，但翻桌率算快，當天排了30分鐘就進場。不得不佩服服務人員的記憶力，排隊時就詢問點什...,2025-05-18,2025-05-18
749120,103143585648270720305,NX,1958,3,20,小時,0.000000,米糕還可以，但蚵仔煎老闆自己都不吃看看嗎？這種口感跟味道，不覺得廚餘桶裡面大部分都是這個商品嗎？,2025-05-18,2025-05-18
749121,117526301388555508081,NX,1959,5,3,小時,0.000000,這家餐廳供應美味的臭豆腐。,2025-05-18,2025-05-18
749122,114821725578524301200,NX,1959,5,11,小時,0.000000,他們家的臭豆腐外酥內嫩，不錯👍 …,2025-05-18,2025-05-18
...,...,...,...,...,...,...,...,...,...,...
749867,112382948299552773999,SL,3903,5,1,天,0.033333,豬排好吃～店員態度親切,2025-05-18,2025-05-18
749868,105689020257456062991,SL,3903,1,1,天,0.033333,相信評論吧。 真的不值 超級無敵甜 甜到吃不下去,2025-05-18,2025-05-18
749869,112376036327695392087,SL,3903,4,1,天,0.033333,挺特別的,2025-05-18,2025-05-18
749870,114868234560762459538,SL,3908,1,1,天,0.033333,NaN,2025-05-18,2025-05-18
749871,106258839738116108188,SL,3911,5,23,小時,0.000000,24小時自助泡麵店，泡麵有2面牆這麼多，真的會選擇困難😂 店內有免費自助吧，火腿、玉米、青菜...,2025-05-18,2025-05-18

In [ ]:
df_unique_user = df_date.drop_duplicates(subset=['user_id'], keep='last').copy()
df_unique_user

In [11]:
df_unique_comment = df_date.drop_duplicates(subset=['nm_name', 'st_name', 'user_id', 'rating_star', 'content_clean'], keep='last').copy()
df_unique_comment

,nm_name,st_name,nm_city,st_address,user_name,user_id,is_local_guide,review_count,photo_count,rating_star,time_num,time_unit,months_ago,content_clean,create_date,update_date
761326,寧夏夜市,方家雞肉飯,台北市,大同區寧夏路060攤位號,江先生,110774750567560205736,True,197.0,472.0,3.0,9,小時,0.000000,從小時候30還35開始吃雞肉飯 到現在小小一碗要價50... 連青菜也不炒了 蔥蛋，紫菜蛋花...,2025-05-19,2025-05-19
761327,寧夏夜市,圓環邊蚵仔煎,台北市,大同區寧夏路46號,ダリマティス,105900685368232166565,True,170.0,1.0,3.0,10,小時,0.000000,這是一家可以充分感受到台灣夜市氛圍的餐廳。 我點了外帶蚵仔煎和豬肉糯米飯。牡蠣口感勁道、彈性...,2025-05-19,2025-05-19
761328,寧夏夜市,圓環邊蚵仔煎,台北市,大同區寧夏路46號,TOBIAS WANG,113056049238298869195,True,24.0,65.0,4.0,11,小時,0.000000,排隊名店,2025-05-19,2025-05-19
761329,寧夏夜市,圓環邊蚵仔煎,台北市,大同區寧夏路46號,まーしーまーしー,113777367541280718072,True,12.0,9.0,5.0,21,小時,0.000000,這是我在台灣吃到的最便宜又美味的食物！蚵仔煎！最好的！ 排隊的人很多，所以你得等一會兒或叫外賣。,2025-05-19,2025-05-19
761330,寧夏夜市,圓環邊蚵仔煎,台北市,大同區寧夏路46號,Lance Lin,100726578982543737739,True,21.0,21.0,5.0,1,天,0.033333,蚵仔煎非常好吃 值得一嚐,2025-05-19,2025-05-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
762546,士林夜市,南山炸豬排,台北市,士林區文林路306號,盧情筠110H11120,101272689297295362114,False,1.0,1.0,5.0,1,天,0.033333,好吃,2025-05-19,2025-05-19
762547,士林夜市,南山炸豬排,台北市,士林區文林路306號,林舒薇,110585081343212366942,False,3.0,3.0,5.0,1,天,0.033333,好吃,2025-05-19,2025-05-19
762548,士林夜市,南山炸豬排,台北市,士林區文林路306號,elaine nn,110058296418120527368,True,15.0,6.0,5.0,1,天,0.033333,豬排酥脆 好吃😋,2025-05-19,2025-05-19
762549,士林夜市,南山炸豬排,台北市,士林區文林路306號,CHUN HSIU CHEN,102534612342695444901,False,4.0,2.0,5.0,1,天,0.033333,豬排好吃小菜也好吃！服務生服務周到，會再二訪的一家店。,2025-05-19,2025-05-19
762550,士林夜市,Yiguo Ramen 라면 24H 異國無人拉麵店,台北市,士林區福德路12號14號,琥犽,106258839738116108188,True,538.0,1.0,5.0,1,天,0.033333,24小時自助泡麵店，泡麵有2面牆這麼多，真的會選擇困難😂 店內有免費自助吧，火腿、玉米、青菜...,2025-05-19,2025-05-19

In [ ]:
df_unique_user['review_count'] = df_unique_user['review_count'].fillna(0).astype(int)
df_unique_user['photo_count'] = df_unique_user['photo_count'].fillna(0).astype(int)

In [ ]:
new_order = ['user_name','user_id','is_local_guide','review_count','photo_count','create_date','update_date']
df_unique_user = df_unique_user[new_order]

In [ ]:
df_unique_user

In [12]:
df_nightmarket = pd.read_csv("/workspaces/poetry-demo-test2/toDB/nightmarket_list.csv")
df_store = pd.read_csv("/workspaces/poetry-demo-test2/toDB/store_list.csv")
df_unique_comment = df_unique_comment.merge(df_nightmarket[['nm_id', 'nm_name']], on=['nm_name'], how='left')
df_unique_comment = df_unique_comment.merge(df_store[['st_id', 'nm_id', 'st_name']], on=['nm_id', 'st_name'], how='left')
df_unique_comment

,nm_name,st_name,nm_city,st_address,user_name,user_id,is_local_guide,review_count,photo_count,rating_star,time_num,time_unit,months_ago,content_clean,create_date,update_date,nm_id,st_id
0,寧夏夜市,方家雞肉飯,台北市,大同區寧夏路060攤位號,江先生,110774750567560205736,True,197.0,472.0,3.0,9,小時,0.000000,從小時候30還35開始吃雞肉飯 到現在小小一碗要價50... 連青菜也不炒了 蔥蛋，紫菜蛋花...,2025-05-19,2025-05-19,NX,1957
1,寧夏夜市,圓環邊蚵仔煎,台北市,大同區寧夏路46號,ダリマティス,105900685368232166565,True,170.0,1.0,3.0,10,小時,0.000000,這是一家可以充分感受到台灣夜市氛圍的餐廳。 我點了外帶蚵仔煎和豬肉糯米飯。牡蠣口感勁道、彈性...,2025-05-19,2025-05-19,NX,1958
2,寧夏夜市,圓環邊蚵仔煎,台北市,大同區寧夏路46號,TOBIAS WANG,113056049238298869195,True,24.0,65.0,4.0,11,小時,0.000000,排隊名店,2025-05-19,2025-05-19,NX,1958
3,寧夏夜市,圓環邊蚵仔煎,台北市,大同區寧夏路46號,まーしーまーしー,113777367541280718072,True,12.0,9.0,5.0,21,小時,0.000000,這是我在台灣吃到的最便宜又美味的食物！蚵仔煎！最好的！ 排隊的人很多，所以你得等一會兒或叫外賣。,2025-05-19,2025-05-19,NX,1958
4,寧夏夜市,圓環邊蚵仔煎,台北市,大同區寧夏路46號,Lance Lin,100726578982543737739,True,21.0,21.0,5.0,1,天,0.033333,蚵仔煎非常好吃 值得一嚐,2025-05-19,2025-05-19,NX,1958
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1220,士林夜市,南山炸豬排,台北市,士林區文林路306號,盧情筠110H11120,101272689297295362114,False,1.0,1.0,5.0,1,天,0.033333,好吃,2025-05-19,2025-05-19,SL,3903
1221,士林夜市,南山炸豬排,台北市,士林區文林路306號,林舒薇,110585081343212366942,False,3.0,3.0,5.0,1,天,0.033333,好吃,2025-05-19,2025-05-19,SL,3903
1222,士林夜市,南山炸豬排,台北市,士林區文林路306號,elaine nn,110058296418120527368,True,15.0,6.0,5.0,1,天,0.033333,豬排酥脆 好吃😋,2025-05-19,2025-05-19,SL,3903
1223,士林夜市,南山炸豬排,台北市,士林區文林路306號,CHUN HSIU CHEN,102534612342695444901,False,4.0,2.0,5.0,1,天,0.033333,豬排好吃小菜也好吃！服務生服務周到，會再二訪的一家店。,2025-05-19,2025-05-19,SL,3903
1224,士林夜市,Yiguo Ramen 라면 24H 異國無人拉麵店,台北市,士林區福德路12號14號,琥犽,106258839738116108188,True,538.0,1.0,5.0,1,天,0.033333,24小時自助泡麵店，泡麵有2面牆這麼多，真的會選擇困難😂 店內有免費自助吧，火腿、玉米、青菜...,2025-05-19,2025-05-19,SL,3911

In [ ]:
df_unique_comment.to_csv("/workspaces/poetry-demo-test2/clean/comments_nostid.csv", header=True, index=None)

In [ ]:
df_unique_comment = df_unique_comment[df_unique_comment['st_id'].notna()].copy()
df_unique_comment

In [ ]:
df_unique_comment['time_num'] = df_unique_comment['time_num'].astype(int)
df_unique_comment['months_ago'] = df_unique_comment['months_ago'].astype(float)
df_unique_comment['rating_star'] = df_unique_comment['rating_star'].astype(int)
df_unique_comment['st_id'] = df_unique_comment['st_id'].astype(int)

In [ ]:
new_order = ['user_id', 'nm_id', 'st_id','rating_star', 'time_num', 'time_unit', 'months_ago', 'content_clean', 'create_date', 'update_date']
df_comment_new = df_unique_comment[new_order]
df_comment_new

In [ ]:
df_merge = df_comment_new.merge(df_yesterday, 
                        on=["nm_id", "st_id", "user_id", "rating_star"], 
                        how='left', 
                        indicator=True,
                        suffixes=('', '_y'))

df_today_new = df_merge[df_merge['_merge'] == 'left_only'][df_comment_new.columns]

df_today_new

In [ ]:
df_today_new.to_csv("/workspaces/poetry-demo-test2/toDB/comment_0518_merge.csv")

In [ ]:
df_comment_new

In [ ]:
df_user_old = pd.read_csv("/workspaces/poetry-demo-test2/toDB/user_list.csv")

In [ ]:
df_user_old

In [ ]:
df_new_user = df_unique_user[~df_unique_user['user_id'].isin(df_user_old['user_id'])]

In [ ]:
df_new_user

In [ ]:
df_update_user.to_csv("/workspaces/poetry-demo-test2/toDB/update_user.csv", header=True, index=None)

In [ ]:
df_comment_old = pd.read_csv("/workspaces/poetry-demo-test2/toDB/comment_list.csv")

In [ ]:
df_comment_miss = df[~df['user_id'].isin(df_comment_old['user_id'])]

In [ ]:
df_comment_miss

In [ ]:
df[df['user_id'].isin(df_user['user_id'])]

In [ ]:
df_comment_miss.to_csv("/workspaces/poetry-demo-test2/toDB/comment_list_miss.csv", header=True, index=None)

In [ ]:
df_new_user.to_csv('/workspaces/poetry-demo-test2/toDB/user_list_none.csv', header=True, index=False, encoding='utf-8-sig')

In [ ]:
df_new_user.to_csv('/workspaces/poetry-demo-test2/toDB/user_list.csv', mode='a', header=False, index=False, encoding='utf-8-sig')

In [ ]:
df_comment_new.to_csv('/workspaces/poetry-demo-test2/toDB/comment_list.csv', mode='a', header=False, index=False, encoding='utf-8-sig')

In [ ]:
df = df.drop(columns=['fake_comment', 'fake_level', 'fake_reason'])

In [ ]:
df

In [ ]:
import pymysql
from sqlalchemy import create_engine

host = '35.194.188.197'
port = 3306
user = 'user'
password = 'password'
db = 'BWA'
charset = 'utf8mb4'

engine = create_engine(f'mysql+pymysql://{user}:{password}@{host}:{port}/{db}')

In [ ]:
df_new_user.to_sql(name='USER' , con=engine, if_exists='append', index=False)

In [ ]:
df_comment_new.to_sql(name='COMMENT', con=engine, if_exists='append', index=False)