In [13]:
import pandas as pd

In [14]:
df = pd.read_csv("/workspaces/poetry-demo-test2/clean/store_list_new_name.csv")
df.columns

Index(['st_id', 'nm_id', 'st_name_clean', 'st_name_x', 'st_area', 'st_road',
       'st_score', 'st_price', 'st_total_com', 'st_address_x',
       'st_category_01', 'st_category_02', 'st_category_03', 'longitude',
       'latitude', 'st_tag', 'nm_name', 'st_address_y', 'st_name_y'],
      dtype='object')

In [15]:
df = df.drop(columns=['st_name_clean', 'st_address_x'])
df

,st_id,nm_id,st_name_x,st_area,st_road,st_score,st_price,st_total_com,st_category_01,st_category_02,st_category_03,longitude,latitude,st_tag,nm_name,st_address_y,st_name_y
0,1957,NX,方家雞肉飯,大同區,寧夏路,4.0,$1-200,1549,NaN,NaN,NaN,25.0563,121.515,"滷肉飯,炒青菜,蔥,排骨,雞油,醬,必比登,矩陣,堂食,玉子燒",寧夏夜市,大同區寧夏路060攤位號,方家雞肉飯
1,1958,NX,圓環邊蚵仔煎,大同區,寧夏路,4.0,$1-200,3722,NaN,NaN,NaN,25.0564,121.515,"米糕,米其林,元慶蠔,太白粉,矩陣,佇列,輸送帶,蘿蔔排骨湯,蛤蜊湯,1965年",寧夏夜市,大同區寧夏路46號,圓環邊蚵仔煎
2,1959,NX,李掌伯（原寧夏夜市里長伯麻辣臭豆腐鴨血蚵仔麵線）,大同區,寧夏路,3.7,$1-200,3057,NaN,NaN,NaN,25.0554,121.515,"麻辣鴨血,抄手,腸旺,大腸麵線,炸豆腐,破布子,王子麵,金莎,炸豆腐,辣湯",寧夏夜市,大同區寧夏路22之9號,李掌伯麻辣臭豆腐鴨血蚵仔麵線
3,1960,NX,豬肝榮仔,大同區,寧夏路,4.2,$1-200,1076,NaN,NaN,NaN,25.0569,121.516,"豬肝湯,肉粽,芋頭糕,肉羹,必比登,排隊,冬菜,肚湯,內臟,形狀",寧夏夜市,大同區寧夏路010攤位,豬肝榮仔
4,1961,NX,寧夏夜市-爆漿脆皮魷魚,大同區,寧夏夜市,4.1,$1-200,606,NaN,NaN,NaN,25.0561,121.515,"小黃瓜,椒鹽,炸魷魚,排隊,豆薯,芥末,粉,水梨,荸薺,尤卡",寧夏夜市,大同區寧夏夜市第89攤,爆漿脆皮魷魚
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1951,3908,SL,REEDS PIZZERIA & COFFEE 士林店,士林區,文林路,4.3,$200-400,20,NaN,NaN,NaN,25.0924,121.525,"麵包,空間,咖啡廳,價位,歐洲梨,美式咖啡,裝修,酥脆,烤,環境",士林夜市,士林區文林路340-1號,REEDS PIZZERIA & COFFEE
1952,3909,SL,大塊牛排 - 士林店,士林區,文林路,3.8,$200-400,2512,NaN,NaN,NaN,25.0924,121.525,"夜市,煎,可頌,螺旋麵,玉米濃湯,紅茶,汽水,雞腿,碼點,大學",士林夜市,士林區文林路341號,大塊牛排
1953,3910,SL,海鮮粥,士林區,福德路,4.0,$1-200,111,NaN,NaN,NaN,25.0924,121.525,"炒麵,羊肉,蛋,價格,油,炒飯,蚵,蔥,蝦仁,虱目魚",士林夜市,士林區福德路20號,海鮮粥
1954,3911,SL,Yiguo Ramen 라면 24H 異國無人拉麵店,士林區,福德路,4.9,$1-200,1556,NaN,NaN,NaN,25.0924,121.525,"選擇,環境,宵夜,火鍋,起司,自助吧,包,酷,動線,餐盤",士林夜市,士林區福德路12號14號,Yiguo Ramen
1955,3912,SL,圓通素食館,士林區,大東路,4.3,$1-200,365,NaN,NaN,NaN,25.0924,121.525,"價格,菜,自助餐,飯,打折,晚餐,秤,地板,佛,油",士林夜市,士林區大東路158號,圓通素食館

In [16]:
df['st_address'] = df['st_address_y']
df['st_name_clean'] = df['st_name_y']

In [18]:
df['st_name'] = df['st_name_x']
df.drop(columns=['st_name_x'])

,st_id,nm_id,st_area,st_road,st_score,st_price,st_total_com,st_category_01,st_category_02,st_category_03,longitude,latitude,st_tag,nm_name,st_address_y,st_name_y,st_address,st_name_clean,st_name
0,1957,NX,大同區,寧夏路,4.0,$1-200,1549,NaN,NaN,NaN,25.0563,121.515,"滷肉飯,炒青菜,蔥,排骨,雞油,醬,必比登,矩陣,堂食,玉子燒",寧夏夜市,大同區寧夏路060攤位號,方家雞肉飯,大同區寧夏路060攤位號,方家雞肉飯,方家雞肉飯
1,1958,NX,大同區,寧夏路,4.0,$1-200,3722,NaN,NaN,NaN,25.0564,121.515,"米糕,米其林,元慶蠔,太白粉,矩陣,佇列,輸送帶,蘿蔔排骨湯,蛤蜊湯,1965年",寧夏夜市,大同區寧夏路46號,圓環邊蚵仔煎,大同區寧夏路46號,圓環邊蚵仔煎,圓環邊蚵仔煎
2,1959,NX,大同區,寧夏路,3.7,$1-200,3057,NaN,NaN,NaN,25.0554,121.515,"麻辣鴨血,抄手,腸旺,大腸麵線,炸豆腐,破布子,王子麵,金莎,炸豆腐,辣湯",寧夏夜市,大同區寧夏路22之9號,李掌伯麻辣臭豆腐鴨血蚵仔麵線,大同區寧夏路22之9號,李掌伯麻辣臭豆腐鴨血蚵仔麵線,李掌伯（原寧夏夜市里長伯麻辣臭豆腐鴨血蚵仔麵線）
3,1960,NX,大同區,寧夏路,4.2,$1-200,1076,NaN,NaN,NaN,25.0569,121.516,"豬肝湯,肉粽,芋頭糕,肉羹,必比登,排隊,冬菜,肚湯,內臟,形狀",寧夏夜市,大同區寧夏路010攤位,豬肝榮仔,大同區寧夏路010攤位,豬肝榮仔,豬肝榮仔
4,1961,NX,大同區,寧夏夜市,4.1,$1-200,606,NaN,NaN,NaN,25.0561,121.515,"小黃瓜,椒鹽,炸魷魚,排隊,豆薯,芥末,粉,水梨,荸薺,尤卡",寧夏夜市,大同區寧夏夜市第89攤,爆漿脆皮魷魚,大同區寧夏夜市第89攤,爆漿脆皮魷魚,寧夏夜市-爆漿脆皮魷魚
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1951,3908,SL,士林區,文林路,4.3,$200-400,20,NaN,NaN,NaN,25.0924,121.525,"麵包,空間,咖啡廳,價位,歐洲梨,美式咖啡,裝修,酥脆,烤,環境",士林夜市,士林區文林路340-1號,REEDS PIZZERIA & COFFEE,士林區文林路340-1號,REEDS PIZZERIA & COFFEE,REEDS PIZZERIA & COFFEE 士林店
1952,3909,SL,士林區,文林路,3.8,$200-400,2512,NaN,NaN,NaN,25.0924,121.525,"夜市,煎,可頌,螺旋麵,玉米濃湯,紅茶,汽水,雞腿,碼點,大學",士林夜市,士林區文林路341號,大塊牛排,士林區文林路341號,大塊牛排,大塊牛排 - 士林店
1953,3910,SL,士林區,福德路,4.0,$1-200,111,NaN,NaN,NaN,25.0924,121.525,"炒麵,羊肉,蛋,價格,油,炒飯,蚵,蔥,蝦仁,虱目魚",士林夜市,士林區福德路20號,海鮮粥,士林區福德路20號,海鮮粥,海鮮粥
1954,3911,SL,士林區,福德路,4.9,$1-200,1556,NaN,NaN,NaN,25.0924,121.525,"選擇,環境,宵夜,火鍋,起司,自助吧,包,酷,動線,餐盤",士林夜市,士林區福德路12號14號,Yiguo Ramen,士林區福德路12號14號,Yiguo Ramen,Yiguo Ramen 라면 24H 異國無人拉麵店
1955,3912,SL,士林區,大東路,4.3,$1-200,365,NaN,NaN,NaN,25.0924,121.525,"價格,菜,自助餐,飯,打折,晚餐,秤,地板,佛,油",士林夜市,士林區大東路158號,圓通素食館,士林區大東路158號,圓通素食館,圓通素食館

In [19]:
new_order = ['st_id', 'nm_id', 'st_name_clean', 'st_name', 'st_area', 'st_road', 'st_score', 'st_price', 'st_total_com', 'st_address', 'st_category_01', 'st_category_02', 'st_category_03', 'longitude', 'latitude', 'st_tag']
df = df[new_order]
df

,st_id,nm_id,st_name_clean,st_name,st_area,st_road,st_score,st_price,st_total_com,st_address,st_category_01,st_category_02,st_category_03,longitude,latitude,st_tag
0,1957,NX,方家雞肉飯,方家雞肉飯,大同區,寧夏路,4.0,$1-200,1549,大同區寧夏路060攤位號,NaN,NaN,NaN,25.0563,121.515,"滷肉飯,炒青菜,蔥,排骨,雞油,醬,必比登,矩陣,堂食,玉子燒"
1,1958,NX,圓環邊蚵仔煎,圓環邊蚵仔煎,大同區,寧夏路,4.0,$1-200,3722,大同區寧夏路46號,NaN,NaN,NaN,25.0564,121.515,"米糕,米其林,元慶蠔,太白粉,矩陣,佇列,輸送帶,蘿蔔排骨湯,蛤蜊湯,1965年"
2,1959,NX,李掌伯麻辣臭豆腐鴨血蚵仔麵線,李掌伯（原寧夏夜市里長伯麻辣臭豆腐鴨血蚵仔麵線）,大同區,寧夏路,3.7,$1-200,3057,大同區寧夏路22之9號,NaN,NaN,NaN,25.0554,121.515,"麻辣鴨血,抄手,腸旺,大腸麵線,炸豆腐,破布子,王子麵,金莎,炸豆腐,辣湯"
3,1960,NX,豬肝榮仔,豬肝榮仔,大同區,寧夏路,4.2,$1-200,1076,大同區寧夏路010攤位,NaN,NaN,NaN,25.0569,121.516,"豬肝湯,肉粽,芋頭糕,肉羹,必比登,排隊,冬菜,肚湯,內臟,形狀"
4,1961,NX,爆漿脆皮魷魚,寧夏夜市-爆漿脆皮魷魚,大同區,寧夏夜市,4.1,$1-200,606,大同區寧夏夜市第89攤,NaN,NaN,NaN,25.0561,121.515,"小黃瓜,椒鹽,炸魷魚,排隊,豆薯,芥末,粉,水梨,荸薺,尤卡"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1951,3908,SL,REEDS PIZZERIA & COFFEE,REEDS PIZZERIA & COFFEE 士林店,士林區,文林路,4.3,$200-400,20,士林區文林路340-1號,NaN,NaN,NaN,25.0924,121.525,"麵包,空間,咖啡廳,價位,歐洲梨,美式咖啡,裝修,酥脆,烤,環境"
1952,3909,SL,大塊牛排,大塊牛排 - 士林店,士林區,文林路,3.8,$200-400,2512,士林區文林路341號,NaN,NaN,NaN,25.0924,121.525,"夜市,煎,可頌,螺旋麵,玉米濃湯,紅茶,汽水,雞腿,碼點,大學"
1953,3910,SL,海鮮粥,海鮮粥,士林區,福德路,4.0,$1-200,111,士林區福德路20號,NaN,NaN,NaN,25.0924,121.525,"炒麵,羊肉,蛋,價格,油,炒飯,蚵,蔥,蝦仁,虱目魚"
1954,3911,SL,Yiguo Ramen,Yiguo Ramen 라면 24H 異國無人拉麵店,士林區,福德路,4.9,$1-200,1556,士林區福德路12號14號,NaN,NaN,NaN,25.0924,121.525,"選擇,環境,宵夜,火鍋,起司,自助吧,包,酷,動線,餐盤"
1955,3912,SL,圓通素食館,圓通素食館,士林區,大東路,4.3,$1-200,365,士林區大東路158號,NaN,NaN,NaN,25.0924,121.525,"價格,菜,自助餐,飯,打折,晚餐,秤,地板,佛,油"

In [20]:
df.to_csv("/workspaces/poetry-demo-test2/clean/store_list.csv", header=True, index=None)