In [66]:
import pandas as pd

In [79]:
df = pd.read_csv("/workspaces/data-pipeline/resource/yizhong_store.csv")
df

,names,address,links
0,翁記泡沫廣場,404台中市北區精武路326號,https://www.google.com.tw/maps/place/%E7%BF%81...
1,推擠 韓食,404台中市北區精武路320號,https://www.google.com.tw/maps/place/%E6%8E%A8...
2,王子神谷日式厚鬆餅,404台中市北區一中街6號,https://www.google.com.tw/maps/place/%E7%8E%8B...
3,紅茶巴士 Black Tea Bus - 台中一中街站/飲料店/珍珠奶茶,404台中市北區一中街19號,https://www.google.com.tw/maps/place/%E7%B4%85...
4,小象餐廳,404台中市北區太平路19巷5弄38號,https://www.google.com.tw/maps/place/%E5%B0%8F...
...,...,...,...
192,米家一隻雞、醬蟹,404台中市北區錦南街33號,https://www.google.com.tw/maps/place/%E7%B1%B3...
193,知遇甜品｜豆花·仙草·雪花冰·剉冰｜,404台中市北區錦南街21號,https://www.google.com.tw/maps/place/%E7%9F%A5...
194,岩藏拉麵-一中店,404台中市北區錦南街19-18號,https://www.google.com.tw/maps/place/%E5%B2%A9...
195,Paradiso爬樓梯/restaurants/義大利麵/義大利麵湯/一中街美食/溫馨舒適的...,404台中市北區錦南街19-10號1樓,https://www.google.com.tw/maps/place/Paradiso%...
196,邁•MIND Brunch 早午餐（公休詳見IG及google最新動態）,404台中市北區雙十路二段35號,https://www.google.com.tw/maps/place/%E9%82%81...

In [80]:
import re

def clean_store_name(raw_name):
    parts = re.split(r'[-|｜/()（）_\[\]。x]',raw_name)  # list
    store_name = parts[0].strip()  # list取0，字串無空格
    store_name = re.sub(r'[，,]', '', store_name) # 取代，成空格
    return store_name

In [81]:
df['names']

0                                                 翁記泡沫廣場
1                                                  推擠 韓食
2                                              王子神谷日式厚鬆餅
3                   紅茶巴士 Black Tea Bus - 台中一中街站/飲料店/珍珠奶茶
4                                                   小象餐廳
                             ...
192                                             米家一隻雞、醬蟹
193                                   知遇甜品｜豆花·仙草·雪花冰·剉冰｜
194                                             岩藏拉麵-一中店
195    Paradiso爬樓梯/restaurants/義大利麵/義大利麵湯/一中街美食/溫馨舒適的...
196                 邁•MIND Brunch 早午餐（公休詳見IG及google最新動態）
Name: names, Length: 197, dtype: object

In [82]:
df['names'].apply(clean_store_name)

0                  翁記泡沫廣場
1                   推擠 韓食
2               王子神谷日式厚鬆餅
3      紅茶巴士 Black Tea Bus
4                    小象餐廳
              ...
192              米家一隻雞、醬蟹
193                  知遇甜品
194                  岩藏拉麵
195           Paradiso爬樓梯
196     邁•MIND Brunch 早午餐
Name: names, Length: 197, dtype: object

In [83]:
df['store_name'] = df['names'].apply(clean_store_name)
df

,names,address,links,store_name
0,翁記泡沫廣場,404台中市北區精武路326號,https://www.google.com.tw/maps/place/%E7%BF%81...,翁記泡沫廣場
1,推擠 韓食,404台中市北區精武路320號,https://www.google.com.tw/maps/place/%E6%8E%A8...,推擠 韓食
2,王子神谷日式厚鬆餅,404台中市北區一中街6號,https://www.google.com.tw/maps/place/%E7%8E%8B...,王子神谷日式厚鬆餅
3,紅茶巴士 Black Tea Bus - 台中一中街站/飲料店/珍珠奶茶,404台中市北區一中街19號,https://www.google.com.tw/maps/place/%E7%B4%85...,紅茶巴士 Black Tea Bus
4,小象餐廳,404台中市北區太平路19巷5弄38號,https://www.google.com.tw/maps/place/%E5%B0%8F...,小象餐廳
...,...,...,...,...
192,米家一隻雞、醬蟹,404台中市北區錦南街33號,https://www.google.com.tw/maps/place/%E7%B1%B3...,米家一隻雞、醬蟹
193,知遇甜品｜豆花·仙草·雪花冰·剉冰｜,404台中市北區錦南街21號,https://www.google.com.tw/maps/place/%E7%9F%A5...,知遇甜品
194,岩藏拉麵-一中店,404台中市北區錦南街19-18號,https://www.google.com.tw/maps/place/%E5%B2%A9...,岩藏拉麵
195,Paradiso爬樓梯/restaurants/義大利麵/義大利麵湯/一中街美食/溫馨舒適的...,404台中市北區錦南街19-10號1樓,https://www.google.com.tw/maps/place/Paradiso%...,Paradiso爬樓梯
196,邁•MIND Brunch 早午餐（公休詳見IG及google最新動態）,404台中市北區雙十路二段35號,https://www.google.com.tw/maps/place/%E9%82%81...,邁•MIND Brunch 早午餐

In [84]:
def split_address(raw_address):
    address = re.sub(r"^\d{3,6}", '', raw_address) # 取代開頭郵遞區號3-6個數字成空字串
    match = re.match(r"^(.{2,4}[縣市].{1,3}[鄉鎮市區])(.+)", address)  
    # (取代開頭2-4任意字元連接縣市，1-3任意字元連接鄉鎮市區為第一群組) (剩下任意字元為第二組)
    if match:
        area = match.group(1)
        detail = match.group(2)
    else:
        area = ''
        detail = address

    return pd.Series({
        "store_area": area,
        "store_address_clean": detail
        }
    )

In [85]:
df['address'].apply(split_address)

    store_area store_address_clean
0        台中市北區             精武路326號
1        台中市北區             精武路320號
2        台中市北區               一中街6號
3        台中市北區              一中街19號
4        台中市北區         太平路19巷5弄38號
..         ...                 ...
192      台中市北區              錦南街33號
193      台中市北區              錦南街21號
194      台中市北區           錦南街19-18號
195      台中市北區         錦南街19-10號1樓
196      台中市北區            雙十路二段35號

[197 rows x 2 columns]

In [60]:
df[['store_area', 'store_address_clean']] = df['address'].apply(split_address)
df

,names,address,links,store_name,store_area,store_address_clean
0,好好味冰火菠蘿油 瑞豐店,804高雄市鼓山區裕誠路1079號,https://www.google.com.tw/maps/place/%E5%A5%BD...,好好味冰火菠蘿油 瑞豐店,高雄市鼓山區,裕誠路1079號
1,甘丹厚切炒酸奶,813高雄市左營區南屏路裕誠路交叉口,https://www.google.com.tw/maps/place/%E7%94%98...,甘丹厚切炒酸奶,高雄市左營區,南屏路裕誠路交叉口
2,何佳佳蔥油餅（瑞豐夜市）,81355高雄市左營區裕誠路南屏路瑞豐夜市第三排,https://www.google.com.tw/maps/place/%E4%BD%95...,何佳佳蔥油餅,高雄市左營區,裕誠路南屏路瑞豐夜市第三排
3,曾氏福建炒麵-全台第一創始店｜十年老字號｜臺灣第一福建炒麵品牌｜瑞豐夜市必吃美食｜小吃｜外帶｜消夜,813高雄市左營區南屏路瑞豐夜市第一排,https://www.google.com.tw/maps/place/%E6%9B%BE...,曾氏福建炒麵,高雄市左營區,南屏路瑞豐夜市第一排
4,阿3酥皮雞蛋糕-瑞豐夜市(南屏路裕誠路三角窗/第一排/免下車取餐）,813高雄市左營區瑞豐夜市,https://www.google.com.tw/maps/place/%E9%98%BF...,阿3酥皮雞蛋糕,高雄市左營區,瑞豐夜市
...,...,...,...,...,...,...
133,彎腰湯圓,804059高雄市鼓山區南屏路537號,https://www.google.com.tw/maps/place/%E5%BD%8E...,彎腰湯圓,高雄市鼓山區,南屏路537號
134,讚呀正宗韓式烤肉,804高雄市鼓山區文信路255號,https://www.google.com.tw/maps/place/%E8%AE%9A...,讚呀正宗韓式烤肉,高雄市鼓山區,文信路255號
135,螺痴粉 高雄螺螄粉專賣餐廳,804高雄市鼓山區昌盛路58號1樓,https://www.google.com.tw/maps/place/%E8%9E%BA...,螺痴粉 高雄螺螄粉專賣餐廳,高雄市鼓山區,昌盛路58號1樓
136,森川丼丼巨蛋店,80465高雄市鼓山區昌盛路55號,https://www.google.com.tw/maps/place/%E6%A3%AE...,森川丼丼巨蛋店,高雄市鼓山區,昌盛路55號
137,華饌湯包麵食館,804高雄市鼓山區文信路208號,https://www.google.com.tw/maps/place/%E8%8F%AF...,華饌湯包麵食館,高雄市鼓山區,文信路208號

In [86]:
df.drop(columns=['names', 'address'])

                                                 links          store_name
0    https://www.google.com.tw/maps/place/%E7%BF%81...              翁記泡沫廣場
1    https://www.google.com.tw/maps/place/%E6%8E%A8...               推擠 韓食
2    https://www.google.com.tw/maps/place/%E7%8E%8B...           王子神谷日式厚鬆餅
3    https://www.google.com.tw/maps/place/%E7%B4%85...  紅茶巴士 Black Tea Bus
4    https://www.google.com.tw/maps/place/%E5%B0%8F...                小象餐廳
..                                                 ...                 ...
192  https://www.google.com.tw/maps/place/%E7%B1%B3...            米家一隻雞、醬蟹
193  https://www.google.com.tw/maps/place/%E7%9F%A5...                知遇甜品
194  https://www.google.com.tw/maps/place/%E5%B2%A9...                岩藏拉麵
195  https://www.google.com.tw/maps/place/Paradiso%...         Paradiso爬樓梯
196  https://www.google.com.tw/maps/place/%E9%82%81...   邁•MIND Brunch 早午餐

[197 rows x 2 columns]

In [62]:
df = df.drop(columns=['names', 'address'])
df

,links,store_name,store_area,store_address_clean
0,https://www.google.com.tw/maps/place/%E5%A5%BD...,好好味冰火菠蘿油 瑞豐店,高雄市鼓山區,裕誠路1079號
1,https://www.google.com.tw/maps/place/%E7%94%98...,甘丹厚切炒酸奶,高雄市左營區,南屏路裕誠路交叉口
2,https://www.google.com.tw/maps/place/%E4%BD%95...,何佳佳蔥油餅,高雄市左營區,裕誠路南屏路瑞豐夜市第三排
3,https://www.google.com.tw/maps/place/%E6%9B%BE...,曾氏福建炒麵,高雄市左營區,南屏路瑞豐夜市第一排
4,https://www.google.com.tw/maps/place/%E9%98%BF...,阿3酥皮雞蛋糕,高雄市左營區,瑞豐夜市
...,...,...,...,...
133,https://www.google.com.tw/maps/place/%E5%BD%8E...,彎腰湯圓,高雄市鼓山區,南屏路537號
134,https://www.google.com.tw/maps/place/%E8%AE%9A...,讚呀正宗韓式烤肉,高雄市鼓山區,文信路255號
135,https://www.google.com.tw/maps/place/%E8%9E%BA...,螺痴粉 高雄螺螄粉專賣餐廳,高雄市鼓山區,昌盛路58號1樓
136,https://www.google.com.tw/maps/place/%E6%A3%AE...,森川丼丼巨蛋店,高雄市鼓山區,昌盛路55號
137,https://www.google.com.tw/maps/place/%E8%8F%AF...,華饌湯包麵食館,高雄市鼓山區,文信路208號

In [87]:
df.to_csv("yizhong_store_clean.csv", header=True, index=None)