In [49]:
import pandas as pd

In [66]:
df = pd.read_csv("/workspaces/data-pipeline/resource/20250425_crawler_ruifang_rawdata.csv")
df

,店家名稱,評分,留言者名稱,留言者身分,留言時間,評論內容
0,好好味冰火菠蘿油 瑞豐店,5 顆星,JOODY AHN,在地嚮導 · 15 則評論 · 23 張相片,2 天前,我在逃離夜市時發現了這個地方，因為它是如此擁擠和令人窒息。我吃了鳳梨麵包+錨黃油。趁熱吃非常...
1,好好味冰火菠蘿油 瑞豐店,1 顆星,陳芃亘,5 則評論,2 天前,上班認真一點 我不是來買純菠蘿麵包\n裡面什麼都沒有 連切口都沒有\n這次才買三顆 兩顆原味...
2,好好味冰火菠蘿油 瑞豐店,5 顆星,Clém,"在地嚮導 · 863 則評論 · 1,715 張相片",6 天前,當我收到它並吃掉它時，麵包已經熱了，黃油也開始融化，所以時機非常好。甜度適中、已經鬆軟的麵包...
3,好好味冰火菠蘿油 瑞豐店,5 顆星,GOOD유라,在地嚮導 · 38 則評論 · 83 張相片,1 週前,2 約翰‧馬特奧克\n應該買ㅜ
4,好好味冰火菠蘿油 瑞豐店,5 顆星,Ta,"在地嚮導 · 296 則評論 · 2,365 張相片",1 週前,菠蘿油很好吃～～～\n外酥內軟不會太甜！\n照片上的男服務員態度超級不好不知道是怎樣….
...,...,...,...,...,...,...
38896,華饌湯包麵食館,2 顆星,金特斯,46 則評論 · 13 張相片,3 年前,這是我這幾年吃過最沒味道又最貴的豬耳朵⋯\n爆炒豬肉很咸\n板條有顏色卻沒什麼味道 …
38897,華饌湯包麵食館,2 顆星,陳小曦,在地嚮導 · 19 則評論 · 15 張相片,3 年前,不曉得我是不是和其它評論者處於平行宇宙，好久沒吃到那麼驚為天人難吃的食物了，酸辣湯過鹹，玉米...
38898,華饌湯包麵食館,5 顆星,ERIN WU,在地嚮導 · 330 則評論 · 438 張相片,3 年前,好吃 又有免費紅茶、豆漿
38899,華饌湯包麵食館,5 顆星,Danny Huang,在地嚮導 · 46 則評論 · 4 張相片,3 年前,NaN
38900,華饌湯包麵食館,5 顆星,張淑娟,5 則評論 · 1 張相片,3 年前,烙餅好吃！

In [67]:
import re

def clean_store_name(raw_name):
    parts = re.split(r'[-|｜/()（）_\[\]。x]',raw_name)  # list
    store_name = parts[0].strip()  # list取0，字串無空格
    store_name = re.sub(r'[，,]', '', store_name) # 取代，成空格
    return store_name

In [68]:
df['店家名稱']

0        好好味冰火菠蘿油 瑞豐店
1        好好味冰火菠蘿油 瑞豐店
2        好好味冰火菠蘿油 瑞豐店
3        好好味冰火菠蘿油 瑞豐店
4        好好味冰火菠蘿油 瑞豐店
             ...
38896         華饌湯包麵食館
38897         華饌湯包麵食館
38898         華饌湯包麵食館
38899         華饌湯包麵食館
38900         華饌湯包麵食館
Name: 店家名稱, Length: 38901, dtype: object

In [69]:
df['store_name'] = df['店家名稱'].apply(clean_store_name)
df

,店家名稱,評分,留言者名稱,留言者身分,留言時間,評論內容,store_name
0,好好味冰火菠蘿油 瑞豐店,5 顆星,JOODY AHN,在地嚮導 · 15 則評論 · 23 張相片,2 天前,我在逃離夜市時發現了這個地方，因為它是如此擁擠和令人窒息。我吃了鳳梨麵包+錨黃油。趁熱吃非常...,好好味冰火菠蘿油 瑞豐店
1,好好味冰火菠蘿油 瑞豐店,1 顆星,陳芃亘,5 則評論,2 天前,上班認真一點 我不是來買純菠蘿麵包\n裡面什麼都沒有 連切口都沒有\n這次才買三顆 兩顆原味...,好好味冰火菠蘿油 瑞豐店
2,好好味冰火菠蘿油 瑞豐店,5 顆星,Clém,"在地嚮導 · 863 則評論 · 1,715 張相片",6 天前,當我收到它並吃掉它時，麵包已經熱了，黃油也開始融化，所以時機非常好。甜度適中、已經鬆軟的麵包...,好好味冰火菠蘿油 瑞豐店
3,好好味冰火菠蘿油 瑞豐店,5 顆星,GOOD유라,在地嚮導 · 38 則評論 · 83 張相片,1 週前,2 約翰‧馬特奧克\n應該買ㅜ,好好味冰火菠蘿油 瑞豐店
4,好好味冰火菠蘿油 瑞豐店,5 顆星,Ta,"在地嚮導 · 296 則評論 · 2,365 張相片",1 週前,菠蘿油很好吃～～～\n外酥內軟不會太甜！\n照片上的男服務員態度超級不好不知道是怎樣….,好好味冰火菠蘿油 瑞豐店
...,...,...,...,...,...,...,...
38896,華饌湯包麵食館,2 顆星,金特斯,46 則評論 · 13 張相片,3 年前,這是我這幾年吃過最沒味道又最貴的豬耳朵⋯\n爆炒豬肉很咸\n板條有顏色卻沒什麼味道 …,華饌湯包麵食館
38897,華饌湯包麵食館,2 顆星,陳小曦,在地嚮導 · 19 則評論 · 15 張相片,3 年前,不曉得我是不是和其它評論者處於平行宇宙，好久沒吃到那麼驚為天人難吃的食物了，酸辣湯過鹹，玉米...,華饌湯包麵食館
38898,華饌湯包麵食館,5 顆星,ERIN WU,在地嚮導 · 330 則評論 · 438 張相片,3 年前,好吃 又有免費紅茶、豆漿,華饌湯包麵食館
38899,華饌湯包麵食館,5 顆星,Danny Huang,在地嚮導 · 46 則評論 · 4 張相片,3 年前,NaN,華饌湯包麵食館
38900,華饌湯包麵食館,5 顆星,張淑娟,5 則評論 · 1 張相片,3 年前,烙餅好吃！,華饌湯包麵食館

In [70]:
# 清理評等
df["評分"].str.extract('(\d+)').astype(int)
# 從字串取出數字變形int

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_915/1840997586.py:2: SyntaxWarning: invalid escape sequence '\d'
  df["評分"].str.extract('(\d+)').astype(int)

       0
0      5
1      1
2      5
3      5
4      5
...   ..
38896  2
38897  2
38898  5
38899  5
38900  5

[38901 rows x 1 columns]

In [71]:
df['rating_star'] = df["評分"].str.extract('(\d+)').astype(int)
df

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_915/1098440532.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['rating_star'] = df["評分"].str.extract('(\d+)').astype(int)

,店家名稱,評分,留言者名稱,留言者身分,留言時間,評論內容,store_name,rating_star
0,好好味冰火菠蘿油 瑞豐店,5 顆星,JOODY AHN,在地嚮導 · 15 則評論 · 23 張相片,2 天前,我在逃離夜市時發現了這個地方，因為它是如此擁擠和令人窒息。我吃了鳳梨麵包+錨黃油。趁熱吃非常...,好好味冰火菠蘿油 瑞豐店,5
1,好好味冰火菠蘿油 瑞豐店,1 顆星,陳芃亘,5 則評論,2 天前,上班認真一點 我不是來買純菠蘿麵包\n裡面什麼都沒有 連切口都沒有\n這次才買三顆 兩顆原味...,好好味冰火菠蘿油 瑞豐店,1
2,好好味冰火菠蘿油 瑞豐店,5 顆星,Clém,"在地嚮導 · 863 則評論 · 1,715 張相片",6 天前,當我收到它並吃掉它時，麵包已經熱了，黃油也開始融化，所以時機非常好。甜度適中、已經鬆軟的麵包...,好好味冰火菠蘿油 瑞豐店,5
3,好好味冰火菠蘿油 瑞豐店,5 顆星,GOOD유라,在地嚮導 · 38 則評論 · 83 張相片,1 週前,2 約翰‧馬特奧克\n應該買ㅜ,好好味冰火菠蘿油 瑞豐店,5
4,好好味冰火菠蘿油 瑞豐店,5 顆星,Ta,"在地嚮導 · 296 則評論 · 2,365 張相片",1 週前,菠蘿油很好吃～～～\n外酥內軟不會太甜！\n照片上的男服務員態度超級不好不知道是怎樣….,好好味冰火菠蘿油 瑞豐店,5
...,...,...,...,...,...,...,...,...
38896,華饌湯包麵食館,2 顆星,金特斯,46 則評論 · 13 張相片,3 年前,這是我這幾年吃過最沒味道又最貴的豬耳朵⋯\n爆炒豬肉很咸\n板條有顏色卻沒什麼味道 …,華饌湯包麵食館,2
38897,華饌湯包麵食館,2 顆星,陳小曦,在地嚮導 · 19 則評論 · 15 張相片,3 年前,不曉得我是不是和其它評論者處於平行宇宙，好久沒吃到那麼驚為天人難吃的食物了，酸辣湯過鹹，玉米...,華饌湯包麵食館,2
38898,華饌湯包麵食館,5 顆星,ERIN WU,在地嚮導 · 330 則評論 · 438 張相片,3 年前,好吃 又有免費紅茶、豆漿,華饌湯包麵食館,5
38899,華饌湯包麵食館,5 顆星,Danny Huang,在地嚮導 · 46 則評論 · 4 張相片,3 年前,NaN,華饌湯包麵食館,5
38900,華饌湯包麵食館,5 顆星,張淑娟,5 則評論 · 1 張相片,3 年前,烙餅好吃！,華饌湯包麵食館,5

In [72]:
df['author'] = df['留言者名稱']
df

,店家名稱,評分,留言者名稱,留言者身分,留言時間,評論內容,store_name,rating_star,author
0,好好味冰火菠蘿油 瑞豐店,5 顆星,JOODY AHN,在地嚮導 · 15 則評論 · 23 張相片,2 天前,我在逃離夜市時發現了這個地方，因為它是如此擁擠和令人窒息。我吃了鳳梨麵包+錨黃油。趁熱吃非常...,好好味冰火菠蘿油 瑞豐店,5,JOODY AHN
1,好好味冰火菠蘿油 瑞豐店,1 顆星,陳芃亘,5 則評論,2 天前,上班認真一點 我不是來買純菠蘿麵包\n裡面什麼都沒有 連切口都沒有\n這次才買三顆 兩顆原味...,好好味冰火菠蘿油 瑞豐店,1,陳芃亘
2,好好味冰火菠蘿油 瑞豐店,5 顆星,Clém,"在地嚮導 · 863 則評論 · 1,715 張相片",6 天前,當我收到它並吃掉它時，麵包已經熱了，黃油也開始融化，所以時機非常好。甜度適中、已經鬆軟的麵包...,好好味冰火菠蘿油 瑞豐店,5,Clém
3,好好味冰火菠蘿油 瑞豐店,5 顆星,GOOD유라,在地嚮導 · 38 則評論 · 83 張相片,1 週前,2 約翰‧馬特奧克\n應該買ㅜ,好好味冰火菠蘿油 瑞豐店,5,GOOD유라
4,好好味冰火菠蘿油 瑞豐店,5 顆星,Ta,"在地嚮導 · 296 則評論 · 2,365 張相片",1 週前,菠蘿油很好吃～～～\n外酥內軟不會太甜！\n照片上的男服務員態度超級不好不知道是怎樣….,好好味冰火菠蘿油 瑞豐店,5,Ta
...,...,...,...,...,...,...,...,...,...
38896,華饌湯包麵食館,2 顆星,金特斯,46 則評論 · 13 張相片,3 年前,這是我這幾年吃過最沒味道又最貴的豬耳朵⋯\n爆炒豬肉很咸\n板條有顏色卻沒什麼味道 …,華饌湯包麵食館,2,金特斯
38897,華饌湯包麵食館,2 顆星,陳小曦,在地嚮導 · 19 則評論 · 15 張相片,3 年前,不曉得我是不是和其它評論者處於平行宇宙，好久沒吃到那麼驚為天人難吃的食物了，酸辣湯過鹹，玉米...,華饌湯包麵食館,2,陳小曦
38898,華饌湯包麵食館,5 顆星,ERIN WU,在地嚮導 · 330 則評論 · 438 張相片,3 年前,好吃 又有免費紅茶、豆漿,華饌湯包麵食館,5,ERIN WU
38899,華饌湯包麵食館,5 顆星,Danny Huang,在地嚮導 · 46 則評論 · 4 張相片,3 年前,NaN,華饌湯包麵食館,5,Danny Huang
38900,華饌湯包麵食館,5 顆星,張淑娟,5 則評論 · 1 張相片,3 年前,烙餅好吃！,華饌湯包麵食館,5,張淑娟

In [73]:
# 清理身分欄位
def prase_user_info(text):
    text = str(text) if not isinstance(text, str) else text
    # 檢查是不是字串，不是的話就是字串類型，才能判斷
    is_local_guide = '在地嚮導' in text
    review_cnt = 0
    photo_cnt = 0
    
    reviews_match = re.search(r"([\d,]+)\s*則評論", text) # 找尋(有多位數字含,為第一組)空格則評論 -> str
    if reviews_match:
        review_cnt = int(reviews_match.group(1).replace(",",""))  # 第一組數字,取代成空字串轉成整數
    else:
        review_cnt == 0

    photos_match = re.search(r"([\d,]+)\s*張相片", text) # 找尋(有多位數字含,為第一組)空格張相片 -> str
    if photos_match:
        photo_cnt = int(photos_match.group(1).replace(",","")) # 第一組數字,取代成空字串轉成整數
    else:
        photo_cnt == 0
    
    return pd.Series({
        "is_local_guide": is_local_guide,
        "review_cnt": review_cnt,
        "photo_cnt": photo_cnt
    })

In [74]:
df['留言者身分'].apply(prase_user_info)

       is_local_guide  review_cnt  photo_cnt
0                True          15         23
1               False           5          0
2                True         863       1715
3                True          38         83
4                True         296       2365
...               ...         ...        ...
38896           False          46         13
38897            True          19         15
38898            True         330        438
38899            True          46          4
38900           False           5          1

[38901 rows x 3 columns]

In [75]:
df[['is_local_guide', 'review_cnt', 'photo_cnt']] = df['留言者身分'].apply(prase_user_info)
df

,店家名稱,評分,留言者名稱,留言者身分,留言時間,評論內容,store_name,rating_star,author,is_local_guide,review_cnt,photo_cnt
0,好好味冰火菠蘿油 瑞豐店,5 顆星,JOODY AHN,在地嚮導 · 15 則評論 · 23 張相片,2 天前,我在逃離夜市時發現了這個地方，因為它是如此擁擠和令人窒息。我吃了鳳梨麵包+錨黃油。趁熱吃非常...,好好味冰火菠蘿油 瑞豐店,5,JOODY AHN,True,15,23
1,好好味冰火菠蘿油 瑞豐店,1 顆星,陳芃亘,5 則評論,2 天前,上班認真一點 我不是來買純菠蘿麵包\n裡面什麼都沒有 連切口都沒有\n這次才買三顆 兩顆原味...,好好味冰火菠蘿油 瑞豐店,1,陳芃亘,False,5,0
2,好好味冰火菠蘿油 瑞豐店,5 顆星,Clém,"在地嚮導 · 863 則評論 · 1,715 張相片",6 天前,當我收到它並吃掉它時，麵包已經熱了，黃油也開始融化，所以時機非常好。甜度適中、已經鬆軟的麵包...,好好味冰火菠蘿油 瑞豐店,5,Clém,True,863,1715
3,好好味冰火菠蘿油 瑞豐店,5 顆星,GOOD유라,在地嚮導 · 38 則評論 · 83 張相片,1 週前,2 約翰‧馬特奧克\n應該買ㅜ,好好味冰火菠蘿油 瑞豐店,5,GOOD유라,True,38,83
4,好好味冰火菠蘿油 瑞豐店,5 顆星,Ta,"在地嚮導 · 296 則評論 · 2,365 張相片",1 週前,菠蘿油很好吃～～～\n外酥內軟不會太甜！\n照片上的男服務員態度超級不好不知道是怎樣….,好好味冰火菠蘿油 瑞豐店,5,Ta,True,296,2365
...,...,...,...,...,...,...,...,...,...,...,...,...
38896,華饌湯包麵食館,2 顆星,金特斯,46 則評論 · 13 張相片,3 年前,這是我這幾年吃過最沒味道又最貴的豬耳朵⋯\n爆炒豬肉很咸\n板條有顏色卻沒什麼味道 …,華饌湯包麵食館,2,金特斯,False,46,13
38897,華饌湯包麵食館,2 顆星,陳小曦,在地嚮導 · 19 則評論 · 15 張相片,3 年前,不曉得我是不是和其它評論者處於平行宇宙，好久沒吃到那麼驚為天人難吃的食物了，酸辣湯過鹹，玉米...,華饌湯包麵食館,2,陳小曦,True,19,15
38898,華饌湯包麵食館,5 顆星,ERIN WU,在地嚮導 · 330 則評論 · 438 張相片,3 年前,好吃 又有免費紅茶、豆漿,華饌湯包麵食館,5,ERIN WU,True,330,438
38899,華饌湯包麵食館,5 顆星,Danny Huang,在地嚮導 · 46 則評論 · 4 張相片,3 年前,NaN,華饌湯包麵食館,5,Danny Huang,True,46,4
38900,華饌湯包麵食館,5 顆星,張淑娟,5 則評論 · 1 張相片,3 年前,烙餅好吃！,華饌湯包麵食館,5,張淑娟,False,5,1

In [76]:
def split_time(text):
    time_match = re.split(r"(\d+)(.+?)前", text)
    time_num = time_match[1]
    time_unit = time_match[2]

    return pd.Series({
        "time_num" : time_num,
        "time_unit" : time_unit
        }
    )

In [77]:
df['留言時間'].apply(split_time)

      time_num time_unit
0            2         天
1            2         天
2            6         天
3            1         週
4            1         週
...        ...       ...
38896        3         年
38897        3         年
38898        3         年
38899        3         年
38900        3         年

[38901 rows x 2 columns]

In [78]:
df[['time_num', 'time_unit']] = df['留言時間'].apply(split_time)
df

,店家名稱,評分,留言者名稱,留言者身分,留言時間,評論內容,store_name,rating_star,author,is_local_guide,review_cnt,photo_cnt,time_num,time_unit
0,好好味冰火菠蘿油 瑞豐店,5 顆星,JOODY AHN,在地嚮導 · 15 則評論 · 23 張相片,2 天前,我在逃離夜市時發現了這個地方，因為它是如此擁擠和令人窒息。我吃了鳳梨麵包+錨黃油。趁熱吃非常...,好好味冰火菠蘿油 瑞豐店,5,JOODY AHN,True,15,23,2,天
1,好好味冰火菠蘿油 瑞豐店,1 顆星,陳芃亘,5 則評論,2 天前,上班認真一點 我不是來買純菠蘿麵包\n裡面什麼都沒有 連切口都沒有\n這次才買三顆 兩顆原味...,好好味冰火菠蘿油 瑞豐店,1,陳芃亘,False,5,0,2,天
2,好好味冰火菠蘿油 瑞豐店,5 顆星,Clém,"在地嚮導 · 863 則評論 · 1,715 張相片",6 天前,當我收到它並吃掉它時，麵包已經熱了，黃油也開始融化，所以時機非常好。甜度適中、已經鬆軟的麵包...,好好味冰火菠蘿油 瑞豐店,5,Clém,True,863,1715,6,天
3,好好味冰火菠蘿油 瑞豐店,5 顆星,GOOD유라,在地嚮導 · 38 則評論 · 83 張相片,1 週前,2 約翰‧馬特奧克\n應該買ㅜ,好好味冰火菠蘿油 瑞豐店,5,GOOD유라,True,38,83,1,週
4,好好味冰火菠蘿油 瑞豐店,5 顆星,Ta,"在地嚮導 · 296 則評論 · 2,365 張相片",1 週前,菠蘿油很好吃～～～\n外酥內軟不會太甜！\n照片上的男服務員態度超級不好不知道是怎樣….,好好味冰火菠蘿油 瑞豐店,5,Ta,True,296,2365,1,週
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38896,華饌湯包麵食館,2 顆星,金特斯,46 則評論 · 13 張相片,3 年前,這是我這幾年吃過最沒味道又最貴的豬耳朵⋯\n爆炒豬肉很咸\n板條有顏色卻沒什麼味道 …,華饌湯包麵食館,2,金特斯,False,46,13,3,年
38897,華饌湯包麵食館,2 顆星,陳小曦,在地嚮導 · 19 則評論 · 15 張相片,3 年前,不曉得我是不是和其它評論者處於平行宇宙，好久沒吃到那麼驚為天人難吃的食物了，酸辣湯過鹹，玉米...,華饌湯包麵食館,2,陳小曦,True,19,15,3,年
38898,華饌湯包麵食館,5 顆星,ERIN WU,在地嚮導 · 330 則評論 · 438 張相片,3 年前,好吃 又有免費紅茶、豆漿,華饌湯包麵食館,5,ERIN WU,True,330,438,3,年
38899,華饌湯包麵食館,5 顆星,Danny Huang,在地嚮導 · 46 則評論 · 4 張相片,3 年前,NaN,華饌湯包麵食館,5,Danny Huang,True,46,4,3,年
38900,華饌湯包麵食館,5 顆星,張淑娟,5 則評論 · 1 張相片,3 年前,烙餅好吃！,華饌湯包麵食館,5,張淑娟,False,5,1,3,年

In [79]:
df['content_clean'] = df['評論內容']
df

,店家名稱,評分,留言者名稱,留言者身分,留言時間,評論內容,store_name,rating_star,author,is_local_guide,review_cnt,photo_cnt,time_num,time_unit,content_clean
0,好好味冰火菠蘿油 瑞豐店,5 顆星,JOODY AHN,在地嚮導 · 15 則評論 · 23 張相片,2 天前,我在逃離夜市時發現了這個地方，因為它是如此擁擠和令人窒息。我吃了鳳梨麵包+錨黃油。趁熱吃非常...,好好味冰火菠蘿油 瑞豐店,5,JOODY AHN,True,15,23,2,天,我在逃離夜市時發現了這個地方，因為它是如此擁擠和令人窒息。我吃了鳳梨麵包+錨黃油。趁熱吃非常...
1,好好味冰火菠蘿油 瑞豐店,1 顆星,陳芃亘,5 則評論,2 天前,上班認真一點 我不是來買純菠蘿麵包\n裡面什麼都沒有 連切口都沒有\n這次才買三顆 兩顆原味...,好好味冰火菠蘿油 瑞豐店,1,陳芃亘,False,5,0,2,天,上班認真一點 我不是來買純菠蘿麵包\n裡面什麼都沒有 連切口都沒有\n這次才買三顆 兩顆原味...
2,好好味冰火菠蘿油 瑞豐店,5 顆星,Clém,"在地嚮導 · 863 則評論 · 1,715 張相片",6 天前,當我收到它並吃掉它時，麵包已經熱了，黃油也開始融化，所以時機非常好。甜度適中、已經鬆軟的麵包...,好好味冰火菠蘿油 瑞豐店,5,Clém,True,863,1715,6,天,當我收到它並吃掉它時，麵包已經熱了，黃油也開始融化，所以時機非常好。甜度適中、已經鬆軟的麵包...
3,好好味冰火菠蘿油 瑞豐店,5 顆星,GOOD유라,在地嚮導 · 38 則評論 · 83 張相片,1 週前,2 約翰‧馬特奧克\n應該買ㅜ,好好味冰火菠蘿油 瑞豐店,5,GOOD유라,True,38,83,1,週,2 約翰‧馬特奧克\n應該買ㅜ
4,好好味冰火菠蘿油 瑞豐店,5 顆星,Ta,"在地嚮導 · 296 則評論 · 2,365 張相片",1 週前,菠蘿油很好吃～～～\n外酥內軟不會太甜！\n照片上的男服務員態度超級不好不知道是怎樣….,好好味冰火菠蘿油 瑞豐店,5,Ta,True,296,2365,1,週,菠蘿油很好吃～～～\n外酥內軟不會太甜！\n照片上的男服務員態度超級不好不知道是怎樣….
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38896,華饌湯包麵食館,2 顆星,金特斯,46 則評論 · 13 張相片,3 年前,這是我這幾年吃過最沒味道又最貴的豬耳朵⋯\n爆炒豬肉很咸\n板條有顏色卻沒什麼味道 …,華饌湯包麵食館,2,金特斯,False,46,13,3,年,這是我這幾年吃過最沒味道又最貴的豬耳朵⋯\n爆炒豬肉很咸\n板條有顏色卻沒什麼味道 …
38897,華饌湯包麵食館,2 顆星,陳小曦,在地嚮導 · 19 則評論 · 15 張相片,3 年前,不曉得我是不是和其它評論者處於平行宇宙，好久沒吃到那麼驚為天人難吃的食物了，酸辣湯過鹹，玉米...,華饌湯包麵食館,2,陳小曦,True,19,15,3,年,不曉得我是不是和其它評論者處於平行宇宙，好久沒吃到那麼驚為天人難吃的食物了，酸辣湯過鹹，玉米...
38898,華饌湯包麵食館,5 顆星,ERIN WU,在地嚮導 · 330 則評論 · 438 張相片,3 年前,好吃 又有免費紅茶、豆漿,華饌湯包麵食館,5,ERIN WU,True,330,438,3,年,好吃 又有免費紅茶、豆漿
38899,華饌湯包麵食館,5 顆星,Danny Huang,在地嚮導 · 46 則評論 · 4 張相片,3 年前,NaN,華饌湯包麵食館,5,Danny Huang,True,46,4,3,年,NaN
38900,華饌湯包麵食館,5 顆星,張淑娟,5 則評論 · 1 張相片,3 年前,烙餅好吃！,華饌湯包麵食館,5,張淑娟,False,5,1,3,年,烙餅好吃！

In [80]:
df = df.drop(columns=['店家名稱', '評分', '留言者名稱', '留言者身分', '留言時間', '評論內容'])
df

,store_name,rating_star,author,is_local_guide,review_cnt,photo_cnt,time_num,time_unit,content_clean
0,好好味冰火菠蘿油 瑞豐店,5,JOODY AHN,True,15,23,2,天,我在逃離夜市時發現了這個地方，因為它是如此擁擠和令人窒息。我吃了鳳梨麵包+錨黃油。趁熱吃非常...
1,好好味冰火菠蘿油 瑞豐店,1,陳芃亘,False,5,0,2,天,上班認真一點 我不是來買純菠蘿麵包\n裡面什麼都沒有 連切口都沒有\n這次才買三顆 兩顆原味...
2,好好味冰火菠蘿油 瑞豐店,5,Clém,True,863,1715,6,天,當我收到它並吃掉它時，麵包已經熱了，黃油也開始融化，所以時機非常好。甜度適中、已經鬆軟的麵包...
3,好好味冰火菠蘿油 瑞豐店,5,GOOD유라,True,38,83,1,週,2 約翰‧馬特奧克\n應該買ㅜ
4,好好味冰火菠蘿油 瑞豐店,5,Ta,True,296,2365,1,週,菠蘿油很好吃～～～\n外酥內軟不會太甜！\n照片上的男服務員態度超級不好不知道是怎樣….
...,...,...,...,...,...,...,...,...,...
38896,華饌湯包麵食館,2,金特斯,False,46,13,3,年,這是我這幾年吃過最沒味道又最貴的豬耳朵⋯\n爆炒豬肉很咸\n板條有顏色卻沒什麼味道 …
38897,華饌湯包麵食館,2,陳小曦,True,19,15,3,年,不曉得我是不是和其它評論者處於平行宇宙，好久沒吃到那麼驚為天人難吃的食物了，酸辣湯過鹹，玉米...
38898,華饌湯包麵食館,5,ERIN WU,True,330,438,3,年,好吃 又有免費紅茶、豆漿
38899,華饌湯包麵食館,5,Danny Huang,True,46,4,3,年,NaN
38900,華饌湯包麵食館,5,張淑娟,False,5,1,3,年,烙餅好吃！

In [81]:
df.to_csv("ruifang_store_comments_clean.csv", header=True, index=None)